* QQ

*Quick debugging for tired developers*

Based off the _excellent_ debugging module `Q` for python by @zestyping

** Usage

#+BEGIN_SRC
def my_func
  foo = "hello world!"
  qq foo
end
#+END_SRC

By default, this prints to `tmp/q`

#+BEGIN_SRC
my_func [10/16/2018 23:48]: foo=`hello world!`
#+END_SRC

** Installation

Add this line to your application's Gemfile:

```ruby
gem 'qq'
```

And then execute:

    $ bundle

Or install it yourself as:

    $ gem install qq

** Development

After checking out the repo, run `bin/setup` to install dependencies. Then, run `rake spec` to run the tests. You can also run `bin/console` for an interactive prompt that will allow you to experiment.

To install this gem onto your local machine, run `bundle exec rake install`. To release a new version, update the version number in `version.rb`, and then run `bundle exec rake release`, which will create a git tag for the version, push git commits and tags, and push the `.gem` file to [rubygems.org](https://rubygems.org).

** Contributing

Bug reports and pull requests are welcome on GitHub at https://github.com/jskulski/qq. This project is intended to be a safe, welcoming space for collaboration, and contributors are expected to adhere to the [Contributor Covenant](http://contributor-covenant.org) code of conduct.

** Code of Conduct

Everyone interacting in the QQ project’s codebases, issue trackers, chat rooms and mailing lists is expected to follow the [code of conduct](https://github.com/jskulski/qq/blob/master/CODE_OF_CONDUCT.md).
